version: 2
updates:
  # 1. Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # 2. Maintain NPM 
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly" 
      day: "saturday"    
      dependencies:
        patterns:
          - "*"

  # 3. Maintain MkDocs
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"